# Copyright 2023-2024 The MathWorks, Inc.

# Workflow that contains jobs to test MATLAB Jupyter Integration
name: Integration testing MATLAB Jupyter Integration

on:
  # Reusable workflow
  workflow_call:

jobs:
  python_integration_tests:
    strategy:
      fail-fast: false
      matrix:
        #TODO: Add test coverage for macOs
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.11"]

        # The minimum matlab-release is set to 21b as 20b and 21a are not supported by matlab-actions/setup-matlab.
        # See https://github.com/matlab-actions/setup-matlab/issues/76
        matlab-release: [R2021b, latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MATLAB ${{ matrix.matlab-release }}
        # Use MATLAB Actions to get running MATLAB in GitHub Actions
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab-release }}
          products: MATLAB Symbolic_Math_Toolbox

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        # Installing wheel package will slightly speed-up installing dependencies.
        # Installing the package with "[dev]" flag  will install test dependecies as well,
        # enabling us to run pytest.
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel pytest
          python3 -m pip install .[dev]

      - name: Ensure browsers are installed for playwright
        run: python3 -m playwright install --with-deps

      - name: Integration test with pytest
        run: python3 -m pytest tests/integration -vs
        env:
          TEST_USERNAME: ${{secrets.TEST_USERNAME}}
          TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}

      - name: Preserve test logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: MATLAB Proxy Integration Test Log File ${{ matrix.os }} matlab-${{ matrix.matlab-release }} python-${{ matrix.python-version }}
          path: |
            tests/integration/integ_logs.log
            licensing-screenshot-failed.png
